language: python
python:
    - "3.5"
before_script:
    - pip install coverage && pip install python-coveralls
install: "python setup.py install"
script: coverage run --source nothashes tests.py && coverage report
after_success:
    - coveralls

